### ISSUE TITLE
facebook currently 403s

### ISSUE THREAD

**Issue by snarfed** [snarfed/activitystreams-unofficial#25]
:(

**Comment by kylewm** [comment]
Looks like this is a scope issue, I tried authenticating with `?scope=public_profile,basic_info,read_stream,manage_notifications,read_friendlists,publish_actions,user_relationships,user_relationship_details,user_likes,user_activities,user_website,user_groups,user_events,user_photos,user_friends,user_about_me,user_status,user_tagged_places` and it works like it's supposed to. 

Of course that is way too many permissions and I'll have to actually read the docs to find out which ones we need :cry:

**Comment by kylewm** [comment]
oh worth mentioning that I changed the API URLs to v2.2 before testing this.

**Comment by snarfed** [comment]
aha, nice sleuthing! i'm guessing `read_stream` will be enough. we might get more data with more of the scopes, but that could be the only one we need to get _something_ and avoid the 403.

**Comment by snarfed** [comment]
confirmed. i tried it with just `read_stream` and `user_status`, and it worked ok.

**Comment by snarfed** [comment]
fixed by upgrading to facebook's graph api v2.2 (see snarfed/bridgy#339)...but i still need to go through the review process to get the `read_stream` permission. leaving this open until i've done that

**Comment by snarfed** [comment]
for future reference, here's the in progress review:
https://developers.facebook.com/apps/355626134468388/review-status/items-in-review/

and the one for [facebook-atom](https://github.com/snarfed/facebook-atom/):
https://developers.facebook.com/apps/545216882163210/review-status/items-in-review/

**Comment by snarfed** [comment]
fixed by snarfed/bridgy#339
